#!/bin/sh

git submodule init
git submodule update

PREVIOUS_HEAD=$1
# if style changed (and less/fabric available), rebuild sourcemaps
if [[
  ! -z "$(git diff $PREVIOUS_HEAD IPython/html/static/style/ipython.min.css)"
  && ! -z "$(git diff $PREVIOUS_HEAD IPython/html/static/style/style.min.css)"
  && ! -z $(which 2>/dev/null lessc)
  && ! -z $(which 2>/dev/null fab)
]]; then
  echo "rebuilding sourcemaps"
  cd IPython/html
  fab css
fi
