#!/bin/bash

git submodule init
git submodule update

if [[ "$(basename $0)" == "post-merge" ]]; then
  PREVIOUS_HEAD=ORIG_HEAD
else
  PREVIOUS_HEAD=$1
fi

# if style changed (and less/invoke available), rebuild sourcemaps
if [[
  ! -z "$(git diff $PREVIOUS_HEAD IPython/html/static/style/ipython.min.css)"
  && ! -z "$(git diff $PREVIOUS_HEAD IPython/html/static/style/style.min.css)"
  && ! -z $(which 2>/dev/null lessc)
  && ! -z $(which 2>/dev/null invoke)
]]; then
  echo "rebuilding sourcemaps"
  cd IPython/html
  invoke css || echo "failed to compile css"
fi
