version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.14"
  apt_packages:
    - graphviz

sphinx:
  configuration: docs/source/conf.py

# Optional but recommended, declare the Python requirements required
# to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
   install:
   - requirements: docs/requirements.txt
