coverage:
  status:
    patch: off
    project:
      default: false
      library:
        target: auto
        paths: ['!.*/tests/.*']
        threshold: 0.1%
      tests:
        target: auto
        paths: ['.*/tests/.*']
        threshold: 0.1%
codecov:
  require_ci_to_pass: false

ignore:
  - IPython/kernel/*
  - IPython/consoleapp.py
  - IPython/core/inputsplitter.py
  - IPython/lib/kernel.py
  - IPython/utils/jsonutil.py
  - IPython/utils/localinterfaces.py
  - IPython/utils/log.py
  - IPython/utils/signatures.py
  - IPython/utils/traitlets.py
