coverage:
  status:
    patch: off
    project:
      default: false
      library:
        target: auto
        paths:
          - '!**/tests/**'
          - '!**/testing/**'
        threshold: 0.1%
      tests:
        target: auto
        paths:
          - '**/tests/**'
          - '**/testing/**'
        threshold: 0.1%
flag_management:
  default_rules:
    statuses:
      - type: patch
        target: auto%
        threshold: 0.1%
      - type: project
        target: auto%
        threshold: 0.1%
  individual_flags:
    - name: unit-tests
      paths:
        - '**/tests/**'
        - '**/testing/**'
    - name: library
      paths:
        - '!**/tests/**'
        - '!**/testing/**'
codecov:
  require_ci_to_pass: false
  branch: main

ignore:
  - IPython/kernel/*
  - IPython/consoleapp.py
  - IPython/lib/kernel.py
  - IPython/utils/jsonutil.py
  - IPython/utils/log.py
  - IPython/utils/signatures.py
