#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""wxIPython -- An enhanced Interactive Python GUI fonrtend
This script starts the Wx graphical frontend.
This is experimental so far.
Currently it support only ipython0 instance. Will be upgraded to ipython1 one.
"""

from IPython.gui.wx import wxIPython

wxIPython.main()
