#!/usr/bin/env python
"""Terminal-based IPython entry point.
"""
import sys
import traceback

from IPython.frontend.terminal.ipapp import launch_new_instance

try:
    launch_new_instance()
except:
    exc_type, exc_value, exc_traceback = sys.exc_info()
    traceback.print_exception(exc_type, exc_value, exc_traceback,
                              file=sys.stderr)
    sys.exit(1)
