#!/bin/sh
set -e

OLD_MODDIR=/usr/lib/python2.2/site-packages/IPython

if [ $1 = "configure" ]; then
    if [ -d $OLD_MODDIR ];then
	echo "Removing old python2.2 modules"
	rm -fr $OLD_MODDIR >&2 
    fi
fi

#DEBHELPER#
