.TH IPYTHONX 1 "October 29, 2008" "" ""
.SH NAME
\fBipythonx \- Simple graphical frontend to IPython, using WxWidgets.
.SH SYNOPSIS
.nf
.fam C
\fBipengine\fP [\fIoptions\fP]
.fam T
.fi
.SH DESCRIPTION
ipythonx is a simple graphical frontend to IPython, using WxWidgets.
.SH OPTIONS
.TP
.B
\-h, \-\-help
show this help message and exit
.TP
.B
\-d, \-\-debug
Enable debug messages for the wx frontend.
look for config files and profiles in this directory
.SH SEE ALSO
.BR ipython(1), ipython-wx(1)
.br
.SH AUTHOR
\fBipythonx\fP is a tool that ships with IPython, created by
the IPython Development Team.
.PP
This manual page was written by Stephan Peijnik <debian@sp.or.at>,
for the Debian project (but may be used by others).
