.TH IPYTHON-WX 1 "October 29, 2008" "" ""
.SH NAME
\fBipython-wx \- Graphical frontend that embeds a multithreaded IPython Shell
.SH SYNOPSIS
.nf
.fam C
\fBipython-wx\fP
.fam T
.fi
.SH DESCRIPTION
ipython-wx is, compared to ipythonx, a more advanced graphical frontend
to IPython. It is implemented using WxWidgets. 
.SH OPTIONS
.TP
.B
ipython-wx does not accept any command line options.
.SH SEE ALSO
.BR ipython(1), ipythonx(1)
.br
.SH AUTHOR
\fBipython-wx\fP is a tool that ships with IPython, created by
the IPython Development Team.
.PP
This manual page was written by Stephan Peijnik <debian@sp.or.at>,
for the Debian project (but may be used by others).
