#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""IPython -- An enhanced Interactive Python

This is just the startup wrapper script, kept deliberately to a minimum.

The shell's mainloop() takes an optional argument, sys_exit (default=0). If
set to 1, it calls sys.exit() at exit time. You can use the following code in
your PYTHONSTARTUP file:

import IPython
IPython.Shell.IPShell().mainloop(sys_exit=1)

[or simply IPython.Shell.IPShell().mainloop(1) ]

and IPython will be your working environment when you start python. The final
sys.exit() call will make python exit transparently when IPython finishes, so
you don't have an extra prompt to get out of.

This is probably useful to developers who manage multiple Python versions and
don't want to have correspondingly multiple IPython versions. Note that in
this mode, there is no way to pass IPython any command-line options, as those
are trapped first by Python itself.
"""

import IPython.Shell

IPython.Shell.start().mainloop()
