.TH IPCLUSTER 1 "June 10, 2012" "" ""
.SH NAME
\fBipcluster \- start a cluster for IPython parallel computing
.SH SYNOPSIS

.B ipcluster subcommand
.RI [ options ]

.SH DESCRIPTION
Start an IPython cluster for parallel computing.

For more information on how to use ipcluster, see 'ipcluster \-\-help',
or 'ipcluster \-\-help\-all' for all available command\(hyline options.

.SH "SEE ALSO"
.BR ipython(1),
.BR ipcontroller(1),
.BR ipengine(1),
.br
.SH AUTHORS
\fBipcluster\fP ships with IPython, maintained by the IPython Development Team.
