.TH IPCONTROLLER 1 "June 10, 2012" "" ""
.SH NAME
\fBipcontroller \- start a controller for IPython parallel computing

.SH SYNOPSIS
.B ipcontroller
.RI [ options ]

.SH DESCRIPTION
ipcontroller starts a controller for the IPython cluster

For more information on how to use ipcontroller, see 'ipcontroller --help',
or 'ipcontroller --help-all' for all available command-line options.

.SH "SEE ALSO"
.BR ipython(1),
.BR ipengine(1),
.BR ipcluster(1)
.br
.SH AUTHORS
\fBipcontroller\fP ships with IPython, maintained by the IPython Development Team.
