.TH IPENGINE 1 "June 10, 2012" "" ""
.SH NAME
\fBipengine \- IPython parallel computing engine
.SH SYNOPSIS
.B ipengine
.RI [ options ]

.SH DESCRIPTION
ipengine starts an engine for the IPython cluster

For more information on how to use ipengine, see 'ipengine \-\-help',
or 'ipengine \-\-help\-all' for all available command\(hyline options.

.SH "SEE ALSO"
.BR ipython(1),
.BR ipcontroller(1),
.BR ipcluster(1)
.br
.SH AUTHORS
\fBipengine\fP ships with IPython, maintained by the IPython Development Team.
