.TH IPLOGGER 1 "June 10, 2012" "" ""
.SH NAME
iplogger \- IPython logging utility for parallel computing.
.SH SYNOPSIS
.B iplogger
.RI [ options ]

.SH DESCRIPTION
Start an IPython log aggregator.

IPython controllers and engines (and your own processes) can broadcast log
messages over zeromq to a single logger instance.

For more information on how to use iplogger, see 'iplogger --help',
or 'iplogger --help-all' for all available command-line options.

.SH "SEE ALSO"
.BR ipython(1),
.BR ipcontroller(1),
.BR ipengine(1),
.BR ipcluster(1)
.br
.SH AUTHOR
\fBiplogger\fP is a tool that ships with IPython, created by
the IPython Development Team.
