.TH IRUNNER 1 "July 15, 2011" "" ""
.SH NAME
\fBirunner \- interactive runner interface
.SH SYNOPSIS
.nf
.fam C
\fBirunner\fP [\fIoptions\fP] \fIfile_to_run\fP
.fam T
.fi
.SH DESCRIPTION
irunner is an interface to the various interactive runners
available in IPython's \fBirunner\fP module. 
It can used to run scripts as if they where typed up
interactively.
.PP
The already implemented runners are listed below; adding
one for a new program is a trivial task, see the source
for examples.
.SH OPTIONS
.TP
.B
\-h, \-\-help
show this help message and exit
.TP
.B
\-\-ipython
IPython interactive runner (default).
.TP
.B
\-\-python
Python interactive runner.
.TP
.B
\-\-sage
SAGE interactive runner.
.SH EXAMPLE
irunner.py \-\-python \-\- \-\-help
will pass \-\-help to the python runner.
Similarly,
irunner.py \-\-ipython \-\- \-\-interact script.ipy
.SH SEE ALSO
.BR ipython(1)
.br
.SH AUTHOR
\fBirunner\fP is an extension of Ken Schutte <kschutte\-AT\-csail.mit.edu>'s
script contributed on the ipython\-user list:
http://mail.scipy.org/pipermail/ipython\-user/2006\-May/003539.html
.PP
This manual page was written by Bernd Zeimetz <bernd@bzed.de>, for the Debian
project (but may be used by others).  Modified by Fernando Perez
<Fernando.Perez@berkeley.edu> for inclusion in IPython.
