.TH IRUNNER 1 "April 24, 2007" "" ""
.SH NAME
\fBirunner \- interactive runner interface
.SH SYNOPSIS
.nf
.fam C
\fBirunner\fP [\fIoptions\fP] \fIfile_to_run\fP
.fam T
.fi
.SH DESCRIPTION
irunner is an interface to the various interactive runners
available in IPython's \fBirunner\fP module. 
.PP
The already implemented runners are listed below; adding
one for a new program is a trivial task, see the source
for examples.
.SH OPTIONS
.TP
.B
\-h, \-\-help
show this help message and exit
.TP
.B
\-\-ipython
IPython interactive runner (default).
.TP
.B
\-\-python
Python interactive runner.
.TP
.B
\-\-sage
SAGE interactive runner.
.SH EXAMPLE
irunner.py \-\-python \-\- \-\-help
will pass \-\-help to the python runner.
Similarly,
irunner.py \-\-ipython \-\- \-\-interact script.ipy
.SH SEE ALSO
.BR ipython(1)
.br
.SH BUGS
The SAGE runner only works if you manually configure your SAGE
copy to use 'colors NoColor' in the ipythonrc config file, since
currently the prompt matching regexp does not identify color sequences.
.SH AUTHOR
\fBirunner\fP is an extension of Ken Schutte <kschutte-AT-csail.mit.edu>'s
script contributed on the ipython-user list:
http://scipy.net/pipermail/ipython-user/2006-May/001705.html
.PP
This manual page was written by Bernd Zeimetz <bernd@bzed.de>,
for the Debian project (but may be used by others).
