#!/bin/bash
# IPython release script

PYVER=`python -V 2>&1 | awk '{print $2}' | awk -F '.' '{print $1$2}' `
version=`ipython -Version`
ipdir=~/ipython/ipython
ipbackupdir=~/ipython/backup

echo
echo "Releasing IPython version $version"
echo "=================================="

# Perform local backup
cd $ipdir/tools
./make_tarball.py
mv ipython-*.tgz $ipbackupdir

# Build release files
./testrel $ipdir

# Register with the Python Package Index (PyPI)
echo "Registering with PyPI..."
cd $ipdir
./setup.py register

# Upload all files
cd $ipdir/dist
echo "Uploading distribution files..."
scp * ipython@ipython.scipy.org:www/dist/

echo "Uploading backup files..."
cd $ipbackupdir
scp `ls -1tr *tgz | tail -1` ipython@ipython.scipy.org:www/backup/

echo "Done!"
