#!/bin/sh

# release test

ipdir=$PWD/..

cd $ipdir

# Clean up build/dist directories
rm -rf $ipdir/build/*
rm -rf $ipdir/dist/*

# build source distros
cd $ipdir
./setup.py sdist --formats=gztar

# Build rpms
python2.4 ./setup.py bdist_rpm --binary-only --release=py24 --python=/usr/bin/python2.4
python2.5 ./setup.py bdist_rpm --binary-only --release=py25 --python=/usr/bin/python2.5

# Build eggs
python2.4 ./setup_bdist_egg.py
python2.5 ./setup_bdist_egg.py

# Call the windows build separately, so that the extra Windows scripts don't
# get pulled into Unix builds (setup.py has code which checks for
# bdist_wininst)
./setup.py bdist_wininst --install-script=ipython_win_post_install.py

# Change name so retarded Vista runs the installer correctly
rename 's/win32/win32-setup/' $ipdir/dist/*.exe
