#!/bin/sh

# release test

# clean up build/dist directories
rm -rf ~/ipython/ipython/build/*
rm -rf ~/ipython/ipython/dist/*

# build source distros
cd ~/ipython/ipython

./setup.py sdist --formats=gztar

# Build rpms
python2.4 ./setup.py bdist_rpm --binary-only --release=py24 --python=/usr/bin/python2.4
python2.5 ./setup.py bdist_rpm --binary-only --release=py25 --python=/usr/bin/python2.5

# Build eggs
python2.4 ./eggsetup.py bdist_egg
python2.5 ./eggsetup.py bdist_egg

# Call the windows build separately, so that the extra Windows scripts don't
# get pulled into Unix builds (setup.py has code which checks for
# bdist_wininst)
./setup.py bdist_wininst --install-script=ipython_win_post_install.py
