name: Build docs

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        environments: docs
    - name: Build docs
      run: |
        pixi run -e docs python -m rstvalidator long_description.rst
        pixi run -e docs python tools/fixup_whats_new_pr.py
        pixi run -e docs make -C docs/ html SPHINXOPTS="-W" \
          PYTHON="coverage run -a" \
          SPHINXBUILD="coverage run -a -m sphinx.cmd.build"
    - name: Generate coverage xml
      run: |
        pixi run -e docs coverage combine `find . -name .coverage\*` && pixi run -e docs coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        name: Docs
