name: Run MyPy

on:
  push:
    branches: [ main, 7.x]
  pull_request:
    branches: [ main, 7.x]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        environments: mypy
    - name: Lint with mypy
      run: |
        set -e
        pixi run -e mypy mypy IPython
    - name: Lint with pyflakes
      run: |
        set -e
        pixi run -e mypy flake8 IPython/core/magics/script.py
        pixi run -e mypy flake8 IPython/core/magics/packaging.py
