name: Nightly Wheel builder
on:
  workflow_dispatch:
  schedule:
    # this cron is ran every Sunday at midnight UTC
    - cron: '0 0 * * 0'

jobs:
  upload_anaconda:
    name: Upload to Anaconda
    runs-on: ubuntu-latest
    # The artifacts cannot be uploaded on PRs, also disable scheduled CI runs on forks
    if: github.event_name != 'pull_request' && (github.event_name != 'schedule' || github.repository_owner == 'ipython')

    steps:
      - uses: actions/checkout@v6
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: build
      - name: Try building with Python build
        if: runner.os != 'Windows'  # setup.py does not support sdist on Windows
        run: |
          pixi run -e build python -m build

      - name: Upload wheel
        uses: scientific-python/upload-nightly-action@main
        with:
          artifacts_path: dist
          anaconda_nightly_upload_token: ${{secrets.UPLOAD_TOKEN}}
