name: Nightly Wheel builder
on:
  workflow_dispatch:
  schedule:
    # this cron is ran every Sunday at midnight UTC
    - cron: '0 0 * * 0'

permissions:
  contents: read

jobs:
  upload_anaconda:
    name: Upload to Anaconda
    runs-on: ubuntu-latest
    # The artifacts cannot be uploaded on PRs, also disable scheduled CI runs on forks
    if: github.event_name != 'pull_request' && (github.event_name != 'schedule' || github.repository_owner == 'ipython')

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.14"
          cache: pip
          cache-dependency-path: |
            pyproject.toml
      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
      - name: Try building with Python build
        if: runner.os != 'Windows'  # setup.py does not support sdist on Windows
        run: |
          uv pip install --system build
          python -m build

      - name: Upload wheel
        uses: scientific-python/upload-nightly-action@9aaae99e2011eef05e293ad9ce15a521694fe9a9 # main
        with:
          artifacts_path: dist
          anaconda_nightly_upload_token: ${{secrets.UPLOAD_TOKEN}}
