name: Run Ruff

on:
  push:
    branches: [ main, 7.x, 8.x]
  pull_request:
    branches: [ main, 7.x, 8.x]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        environments: ruff
    - name: Lint with ruff
      run: |
        set -e
        pixi run -e ruff ruff check .
