name: GitHub Actions Security Analysis with zizmor

on:
  push:
    branches: [ main, 7.x, 8.x ]
  pull_request:
    branches: [ main, 7.x, 8.x ]

permissions:
  contents: read

jobs:
  zizmor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Needed to upload the results to the code-scanning dashboard.
      security-events: write
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - name: Install uv
      uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
    - name: Run zizmor
      id: zizmor
      run: uvx zizmor --format=sarif . > results.sarif
      continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload SARIF results
      if: always()
      uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v3
      with:
        sarif_file: results.sarif
        category: zizmor
    - name: Fail if zizmor found problems
      if: steps.zizmor.outcome == 'failure'
      run: exit 1
